version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:lts-alpine
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
  random1:
    image: 10.154.0.43:5000/random1:build-${BUILD_NUMBER}
    container_name: random1
    build: ./random1
    ports:
    - target: 5001
      published: 5001
  random2:
    container_name: random2
    image: 10.154.0.43:5000/random2:build-${BUILD_NUMBER}
    build: ./random2
    ports:
    - target: 5002
      published: 5002
  combine:
    container_name: combine
    image: 10.154.0.43:5000/combine:build-${BUILD_NUMBER}
    build: ./combine
    ports:
    - target: 5003
      published: 5003
  flask:
    container_name: flask
    image: 10.154.0.43:5000/flask:build-${BUILD_NUMBER}
    build: ./flask
    ports:
    - target: 5000
      published: 5000
    environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_HOST=${MYSQL_HOST}
    - MYSQL_DATAB=${MYSQL_DATAB}
    - YOUR_SECRET_KEY=${YOUR_SECRET_KEY}
