version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
  random1:
    container_name: random1
    build: ./random1
  random2:
    container_name: random2
    build: ./random2
  combine:
    container_name: combine
    build: ./combine
  flask:
    container_name: flask
    build: ./flask
    environment:
    - ENV MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_HOST=${MYSQL_HOST}
    - MYSQL_DATAB=${MYSQL_DATAB}
    - YOUR_SECRET_KEY=${YOUR_SECRET_KEY}
